---
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes
- name: install deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start
# - name: "Create directory for backend"
#   file:
#     path: ~/backend-app
#     state: directory

# - name: "Extract zipped artifact"
#   unarchive:
#     src: artifact.tar.gz
#     dest: ~/backend-app

# - name: "Installing dependencies"
#   shell: |
#     cd ~/backend-app
#     npm i
# - name: "Executing app using pm2"
#   shell: |
#     cd ~/backend-app/dist
#     pm2 stop default
#     pm2 start main.js
#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   shell: |
#     sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#     pm2 save
