---
- name: Copy backend files
  become: true
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Start PM2
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    mv home/circleci/project/backend .
    cd backend
    sudo npm install -g npm@latest
    sudo npm install -g webpack-dev-server
    sudo npm install
    sudo npm run build
    sudo pm2 start npm --name backend -- start
# - name: "Create directory for backend"
#   file:
#     path: ~/backend-app
#     state: directory

# - name: "Extract zipped artifact"
#   unarchive:
#     src: artifact.tar.gz
#     dest: ~/backend-app

# - name: "Installing dependencies"
#   shell: |
#     cd ~/backend-app
#     npm i
# - name: "Executing app using pm2"
#   shell: |
#     cd ~/backend-app/dist
#     pm2 stop default
#     pm2 start main.js
#     # pm2 start npm -- start
#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   become: true
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu